{"time":"2025-02-12T11:44:28.5254852+03:00","level":"INFO","msg":"stream: starting","core version":"0.19.6","symlink path":"C:\\Users\\midas\\midas_model_experimental_umit\\time_series\\wandb\\run-20250212_114428-p0uay712\\logs\\debug-core.log"}
{"time":"2025-02-12T11:44:28.7503051+03:00","level":"INFO","msg":"created new stream","id":"p0uay712"}
{"time":"2025-02-12T11:44:28.7503051+03:00","level":"INFO","msg":"stream: started","id":"p0uay712"}
{"time":"2025-02-12T11:44:28.7503051+03:00","level":"INFO","msg":"handler: started","stream_id":"p0uay712"}
{"time":"2025-02-12T11:44:28.7503051+03:00","level":"INFO","msg":"sender: started","stream_id":"p0uay712"}
{"time":"2025-02-12T11:44:28.7503051+03:00","level":"INFO","msg":"writer: Do: started","stream_id":"p0uay712"}
{"time":"2025-02-12T11:44:28.774666+03:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-02-12T11:44:28.776888+03:00","level":"ERROR","msg":"git repo not found","error":"repository does not exist"}
{"time":"2025-02-12T11:44:28.8290335+03:00","level":"ERROR","msg":"runfiles: CreateRunFiles returned error: input:3: Cannot query field \"createRunFiles\" on type \"Mutation\". Did you mean \"createInvite\", \"createRunQueue\", \"createEntity\", or \"createArtifactFiles\"?\n"}
{"time":"2025-02-12T11:44:28.9505995+03:00","level":"ERROR","msg":"runfiles: CreateRunFiles returned error: input:3: Cannot query field \"createRunFiles\" on type \"Mutation\". Did you mean \"createInvite\", \"createRunQueue\", \"createEntity\", or \"createArtifactFiles\"?\n"}
{"time":"2025-02-12T11:44:29.0554214+03:00","level":"ERROR","msg":"runfiles: CreateRunFiles returned error: input:3: Cannot query field \"createRunFiles\" on type \"Mutation\". Did you mean \"createInvite\", \"createRunQueue\", \"createEntity\", or \"createArtifactFiles\"?\n"}
{"time":"2025-02-12T12:17:04.7103274+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"http://192.168.21.122:8000/graphql\": read tcp 192.168.21.55:30753->192.168.21.122:8000: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-12T12:17:05.0719979+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"http://192.168.21.122:8000/files/ucetinkaya/bitirme_time_series/p0uay712/file_stream\": dial tcp 192.168.21.122:8000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-12T13:28:05.4654954+03:00","level":"INFO","msg":"stream: closing","id":"p0uay712"}
{"time":"2025-02-12T13:28:05.4654954+03:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-02-12T13:28:05.4666026+03:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-02-12T13:28:05.5335227+03:00","level":"ERROR","msg":"runfiles: CreateRunFiles returned error: input:3: Cannot query field \"createRunFiles\" on type \"Mutation\". Did you mean \"createInvite\", \"createRunQueue\", \"createEntity\", or \"createArtifactFiles\"?\n"}
{"time":"2025-02-12T13:28:05.5340769+03:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-02-12T13:28:05.5443685+03:00","level":"INFO","msg":"handler: closed","stream_id":"p0uay712"}
{"time":"2025-02-12T13:28:05.5443685+03:00","level":"INFO","msg":"sender: closed","stream_id":"p0uay712"}
{"time":"2025-02-12T13:28:05.5443685+03:00","level":"INFO","msg":"writer: Close: closed","stream_id":"p0uay712"}
{"time":"2025-02-12T13:28:05.5443685+03:00","level":"INFO","msg":"stream: closed","id":"p0uay712"}
